%%{init: {"flowchart": {"defaultRenderer": "elk"}}}%%
graph TD
    Ceramics[Advanced Ceramics and Refractories — High-temp bricks, Crucibles, Kilns]
    Application[Better Furnaces, Insulation, Seals, Cleanroom Components]
    
    Ceramics --> Application
